# ===========================================================================
# Conda environment for SGT400 Anomaly Detection endpoint
# ===========================================================================
name: sgt400-anomaly-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - numpy==1.26.0
      - pandas==2.2.0
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - mlflow==2.12.0
      - azureml-inference-server-http
      - inference-schema[numpy-support]>=1.3
